{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import urllib.request\n",
    "from bs4 import BeautifulSoup\n",
    "import json\n",
    "import requests\n",
    "import re\n",
    "import pandas as pd\n",
    "import time\n",
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# data extraction\n",
    "def html_parsing(line):\n",
    "    record = []\n",
    "    title = line.find(\"a\", class_= re.compile('title*')).text\n",
    "    time_submitted_obj = line.find(\"time\")\n",
    "    time_sub = time_submitted_obj['datetime']\n",
    "    author = line.find(\"a\", class_='author').text\n",
    "    comments = line.find(\"a\", class_= ('bylink'))['href']\n",
    "    record = [title, time_sub, author, comments]\n",
    "    return record"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Top threads"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# web crawling  \n",
    "url = \"https://old.reddit.com/top/\"\n",
    "r = requests.get(url, headers = {'User-agent': 'your bot 0.1'})\n",
    "soup = BeautifulSoup(r.text, 'html.parser')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "table = soup.find(\"div\", id = 'siteTable')\n",
    "block  = table.findAll(\"div\",attrs={'class':re.compile(\"thing*\")})\n",
    "\n",
    "records = []\n",
    "for line in block:\n",
    "    record = html_parsing(line)\n",
    "    records.append(record)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style>\n",
       "    .dataframe thead tr:only-child th {\n",
       "        text-align: right;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: left;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>time_submitted</th>\n",
       "      <th>author</th>\n",
       "      <th>comments link</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Minnesota's finest responding to noise complai...</td>\n",
       "      <td>2018-12-11T23:49:39+00:00</td>\n",
       "      <td>Cutty__Slouch</td>\n",
       "      <td>https://old.reddit.com/r/funny/comments/a5cio7...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Smooches from his fren makes him very happy</td>\n",
       "      <td>2018-12-11T22:15:45+00:00</td>\n",
       "      <td>Chris_Isur_Dude</td>\n",
       "      <td>https://old.reddit.com/r/aww/comments/a5bnv2/s...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Shout out to Eric Barone (aka ConcernedApe), t...</td>\n",
       "      <td>2018-12-11T22:34:45+00:00</td>\n",
       "      <td>K-LAWN</td>\n",
       "      <td>https://old.reddit.com/r/gaming/comments/a5bu9...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>The strength of humanity</td>\n",
       "      <td>2018-12-11T21:35:02+00:00</td>\n",
       "      <td>commonvanilla</td>\n",
       "      <td>https://old.reddit.com/r/MadeMeSmile/comments/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>It may not be the newest but I was finally abl...</td>\n",
       "      <td>2018-12-12T13:34:16+00:00</td>\n",
       "      <td>Guyonreddit_</td>\n",
       "      <td>https://old.reddit.com/r/gaming/comments/a5i6d...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>In the process of building my dream home. This...</td>\n",
       "      <td>2018-12-12T13:36:09+00:00</td>\n",
       "      <td>zappasaurus</td>\n",
       "      <td>https://old.reddit.com/r/pics/comments/a5i6ui/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>I hired a trainer for my newly-hatched bearded...</td>\n",
       "      <td>2018-12-12T05:08:41+00:00</td>\n",
       "      <td>SuitcaseFullofSparks</td>\n",
       "      <td>https://old.reddit.com/r/funny/comments/a5f20b...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Baby otter exploring water for the first time</td>\n",
       "      <td>2018-12-12T11:39:58+00:00</td>\n",
       "      <td>infin8fire</td>\n",
       "      <td>https://old.reddit.com/r/aww/comments/a5hecc/b...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>This is Clover. She’s a pippet (a cross betwee...</td>\n",
       "      <td>2018-12-12T02:08:11+00:00</td>\n",
       "      <td>CTBUIMH</td>\n",
       "      <td>https://old.reddit.com/r/aww/comments/a5do0l/t...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>My eggs look like they are frowning back at me</td>\n",
       "      <td>2018-12-12T01:54:03+00:00</td>\n",
       "      <td>TheUltimateToasters</td>\n",
       "      <td>https://old.reddit.com/r/mildlyinteresting/com...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Encountered a small blind cat while hiking in ...</td>\n",
       "      <td>2018-12-11T20:56:20+00:00</td>\n",
       "      <td>Angerfist</td>\n",
       "      <td>https://old.reddit.com/r/pics/comments/a5awfb/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>I used my laser cutter/engraver to make this r...</td>\n",
       "      <td>2018-12-12T03:41:15+00:00</td>\n",
       "      <td>wiseroner</td>\n",
       "      <td>https://old.reddit.com/r/pics/comments/a5eepl/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Hydraulic press vs wolverine</td>\n",
       "      <td>2018-12-11T19:49:37+00:00</td>\n",
       "      <td>toomanynamestakenree</td>\n",
       "      <td>https://old.reddit.com/r/oddlysatisfying/comme...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>War&lt;Friendship</td>\n",
       "      <td>2018-12-11T21:54:40+00:00</td>\n",
       "      <td>empa111</td>\n",
       "      <td>https://old.reddit.com/r/PrequelMemes/comments...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Hugh Jackman had a lovely time in Korea</td>\n",
       "      <td>2018-12-12T06:52:33+00:00</td>\n",
       "      <td>Eric__Fapton</td>\n",
       "      <td>https://old.reddit.com/r/gifs/comments/a5frf2/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>If you were offered immortality, but everytime...</td>\n",
       "      <td>2018-12-11T23:45:07+00:00</td>\n",
       "      <td>Kn1ghtV1sta</td>\n",
       "      <td>https://old.reddit.com/r/AskReddit/comments/a5...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Mickey Rourke, and Axl Rose, look like they ar...</td>\n",
       "      <td>2018-12-11T23:26:07+00:00</td>\n",
       "      <td>BBQGenius</td>\n",
       "      <td>https://old.reddit.com/r/pics/comments/a5cbav/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Out here losing before you even get to the sta...</td>\n",
       "      <td>2018-12-11T19:30:20+00:00</td>\n",
       "      <td>SoggyEmploy</td>\n",
       "      <td>https://old.reddit.com/r/BlackPeopleTwitter/co...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>It’s not over until it’s over</td>\n",
       "      <td>2018-12-12T01:39:49+00:00</td>\n",
       "      <td>Chris_Isur_Dude</td>\n",
       "      <td>https://old.reddit.com/r/WatchPeopleDieInside/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Vatican No. 3 Cardinal George Pell Convicted o...</td>\n",
       "      <td>2018-12-12T06:00:44+00:00</td>\n",
       "      <td>AdmiralAkbar1</td>\n",
       "      <td>https://old.reddit.com/r/worldnews/comments/a5...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Timelapse of making the sushi scene from “Isle...</td>\n",
       "      <td>2018-12-12T01:54:05+00:00</td>\n",
       "      <td>nchndmld</td>\n",
       "      <td>https://old.reddit.com/r/oddlysatisfying/comme...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>The pole in this picture makes it look like tw...</td>\n",
       "      <td>2018-12-12T10:40:43+00:00</td>\n",
       "      <td>morphdarko</td>\n",
       "      <td>https://old.reddit.com/r/mildlyinteresting/com...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>He's a friend of the people.</td>\n",
       "      <td>2018-12-12T08:35:38+00:00</td>\n",
       "      <td>smirkingmoon</td>\n",
       "      <td>https://old.reddit.com/r/memes/comments/a5gdby...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>🔥 Lion, The King of the Jungle [Wait for the y...</td>\n",
       "      <td>2018-12-11T22:12:40+00:00</td>\n",
       "      <td>JerryDIY</td>\n",
       "      <td>https://old.reddit.com/r/NatureIsFuckingLit/co...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>Guy makes an upside-down, fire-spewing smoke t...</td>\n",
       "      <td>2018-12-12T00:56:11+00:00</td>\n",
       "      <td>dickfromaccounting</td>\n",
       "      <td>https://old.reddit.com/r/woahdude/comments/a5d...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                title  \\\n",
       "0   Minnesota's finest responding to noise complai...   \n",
       "1         Smooches from his fren makes him very happy   \n",
       "2   Shout out to Eric Barone (aka ConcernedApe), t...   \n",
       "3                            The strength of humanity   \n",
       "4   It may not be the newest but I was finally abl...   \n",
       "5   In the process of building my dream home. This...   \n",
       "6   I hired a trainer for my newly-hatched bearded...   \n",
       "7       Baby otter exploring water for the first time   \n",
       "8   This is Clover. She’s a pippet (a cross betwee...   \n",
       "9      My eggs look like they are frowning back at me   \n",
       "10  Encountered a small blind cat while hiking in ...   \n",
       "11  I used my laser cutter/engraver to make this r...   \n",
       "12                       Hydraulic press vs wolverine   \n",
       "13                                     War<Friendship   \n",
       "14            Hugh Jackman had a lovely time in Korea   \n",
       "15  If you were offered immortality, but everytime...   \n",
       "16  Mickey Rourke, and Axl Rose, look like they ar...   \n",
       "17  Out here losing before you even get to the sta...   \n",
       "18                      It’s not over until it’s over   \n",
       "19  Vatican No. 3 Cardinal George Pell Convicted o...   \n",
       "20  Timelapse of making the sushi scene from “Isle...   \n",
       "21  The pole in this picture makes it look like tw...   \n",
       "22                       He's a friend of the people.   \n",
       "23  🔥 Lion, The King of the Jungle [Wait for the y...   \n",
       "24  Guy makes an upside-down, fire-spewing smoke t...   \n",
       "\n",
       "               time_submitted                author  \\\n",
       "0   2018-12-11T23:49:39+00:00         Cutty__Slouch   \n",
       "1   2018-12-11T22:15:45+00:00       Chris_Isur_Dude   \n",
       "2   2018-12-11T22:34:45+00:00                K-LAWN   \n",
       "3   2018-12-11T21:35:02+00:00         commonvanilla   \n",
       "4   2018-12-12T13:34:16+00:00          Guyonreddit_   \n",
       "5   2018-12-12T13:36:09+00:00           zappasaurus   \n",
       "6   2018-12-12T05:08:41+00:00  SuitcaseFullofSparks   \n",
       "7   2018-12-12T11:39:58+00:00            infin8fire   \n",
       "8   2018-12-12T02:08:11+00:00               CTBUIMH   \n",
       "9   2018-12-12T01:54:03+00:00   TheUltimateToasters   \n",
       "10  2018-12-11T20:56:20+00:00             Angerfist   \n",
       "11  2018-12-12T03:41:15+00:00             wiseroner   \n",
       "12  2018-12-11T19:49:37+00:00  toomanynamestakenree   \n",
       "13  2018-12-11T21:54:40+00:00               empa111   \n",
       "14  2018-12-12T06:52:33+00:00          Eric__Fapton   \n",
       "15  2018-12-11T23:45:07+00:00           Kn1ghtV1sta   \n",
       "16  2018-12-11T23:26:07+00:00             BBQGenius   \n",
       "17  2018-12-11T19:30:20+00:00           SoggyEmploy   \n",
       "18  2018-12-12T01:39:49+00:00       Chris_Isur_Dude   \n",
       "19  2018-12-12T06:00:44+00:00         AdmiralAkbar1   \n",
       "20  2018-12-12T01:54:05+00:00              nchndmld   \n",
       "21  2018-12-12T10:40:43+00:00            morphdarko   \n",
       "22  2018-12-12T08:35:38+00:00          smirkingmoon   \n",
       "23  2018-12-11T22:12:40+00:00              JerryDIY   \n",
       "24  2018-12-12T00:56:11+00:00    dickfromaccounting   \n",
       "\n",
       "                                        comments link  \n",
       "0   https://old.reddit.com/r/funny/comments/a5cio7...  \n",
       "1   https://old.reddit.com/r/aww/comments/a5bnv2/s...  \n",
       "2   https://old.reddit.com/r/gaming/comments/a5bu9...  \n",
       "3   https://old.reddit.com/r/MadeMeSmile/comments/...  \n",
       "4   https://old.reddit.com/r/gaming/comments/a5i6d...  \n",
       "5   https://old.reddit.com/r/pics/comments/a5i6ui/...  \n",
       "6   https://old.reddit.com/r/funny/comments/a5f20b...  \n",
       "7   https://old.reddit.com/r/aww/comments/a5hecc/b...  \n",
       "8   https://old.reddit.com/r/aww/comments/a5do0l/t...  \n",
       "9   https://old.reddit.com/r/mildlyinteresting/com...  \n",
       "10  https://old.reddit.com/r/pics/comments/a5awfb/...  \n",
       "11  https://old.reddit.com/r/pics/comments/a5eepl/...  \n",
       "12  https://old.reddit.com/r/oddlysatisfying/comme...  \n",
       "13  https://old.reddit.com/r/PrequelMemes/comments...  \n",
       "14  https://old.reddit.com/r/gifs/comments/a5frf2/...  \n",
       "15  https://old.reddit.com/r/AskReddit/comments/a5...  \n",
       "16  https://old.reddit.com/r/pics/comments/a5cbav/...  \n",
       "17  https://old.reddit.com/r/BlackPeopleTwitter/co...  \n",
       "18  https://old.reddit.com/r/WatchPeopleDieInside/...  \n",
       "19  https://old.reddit.com/r/worldnews/comments/a5...  \n",
       "20  https://old.reddit.com/r/oddlysatisfying/comme...  \n",
       "21  https://old.reddit.com/r/mildlyinteresting/com...  \n",
       "22  https://old.reddit.com/r/memes/comments/a5gdby...  \n",
       "23  https://old.reddit.com/r/NatureIsFuckingLit/co...  \n",
       "24  https://old.reddit.com/r/woahdude/comments/a5d...  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# data transformation\n",
    "df = pd.DataFrame(records, columns=['title', 'time_submitted', 'author', 'comments link'])\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# save into csv\n",
    "df.to_csv('reddit_data_extraction.csv', sep=',', encoding='UTF-8')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Comments for top threads"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# data extraction\n",
    "def html_parsing_comments(soup_c):\n",
    "    record = []\n",
    "    title = soup_c.find(\"a\", class_= ('title')).text\n",
    "    approve = soup_c.find(\"div\", class_= ('score likes')).text\n",
    "    comment_number = soup_c.find(\"a\", class_= ('bylink')).text.replace(' comments','')\n",
    "    \n",
    "    fst_cmt_all = soup_c.find(\"div\", class_= ('sitetable nestedlisting'))\n",
    "    fst_cmt = fst_cmt_all.find(\"div\", class_= ('entry unvoted'))\n",
    "    \n",
    "    top_comment_author = fst_cmt.find(\"a\", class_= ('author')).text\n",
    "    #top_comment_approve = fst_cmt.find(\"span\", class_= ('score unvoted')).text.replace(' points','')\n",
    "    top_comment = fst_cmt.find(\"div\", class_= ('md')).text\n",
    "    \n",
    "    #record = [title, approve, comment_number, top_comment_author, top_comment_approve, top_comment]\n",
    "    record = [title, approve, comment_number, top_comment_author, top_comment]    \n",
    "    return record"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 / 25  Processing:  https://old.reddit.com/r/funny/comments/a5cio7/minnesotas_finest_responding_to_noise_complaint/\n",
      "2 / 25  Processing:  https://old.reddit.com/r/aww/comments/a5bnv2/smooches_from_his_fren_makes_him_very_happy/\n",
      "3 / 25  Processing:  https://old.reddit.com/r/gaming/comments/a5bu9s/shout_out_to_eric_barone_aka_concernedape_the_man/\n",
      "4 / 25  Processing:  https://old.reddit.com/r/MadeMeSmile/comments/a5ba7e/the_strength_of_humanity/\n",
      "5 / 25  Processing:  https://old.reddit.com/r/gaming/comments/a5i6d8/it_may_not_be_the_newest_but_i_was_finally_able/\n",
      "6 / 25  Processing:  https://old.reddit.com/r/pics/comments/a5i6ui/in_the_process_of_building_my_dream_home_this_is/\n",
      "7 / 25  Processing:  https://old.reddit.com/r/funny/comments/a5f20b/i_hired_a_trainer_for_my_newlyhatched_bearded/\n",
      "8 / 25  Processing:  https://old.reddit.com/r/aww/comments/a5hecc/baby_otter_exploring_water_for_the_first_time/\n",
      "9 / 25  Processing:  https://old.reddit.com/r/aww/comments/a5do0l/this_is_clover_shes_a_pippet_a_cross_between_a/\n",
      "10 / 25  Processing:  https://old.reddit.com/r/mildlyinteresting/comments/a5djx9/my_eggs_look_like_they_are_frowning_back_at_me/\n",
      "11 / 25  Processing:  https://old.reddit.com/r/pics/comments/a5awfb/encountered_a_small_blind_cat_while_hiking_in/\n",
      "12 / 25  Processing:  https://old.reddit.com/r/pics/comments/a5eepl/i_used_my_laser_cutterengraver_to_make_this_rad/\n",
      "13 / 25  Processing:  https://old.reddit.com/r/oddlysatisfying/comments/a5a94x/hydraulic_press_vs_wolverine/\n",
      "14 / 25  Processing:  https://old.reddit.com/r/PrequelMemes/comments/a5bgvv/warfriendship/\n",
      "15 / 25  Processing:  https://old.reddit.com/r/gifs/comments/a5frf2/hugh_jackman_had_a_lovely_time_in_korea/\n",
      "16 / 25  Processing:  https://old.reddit.com/r/AskReddit/comments/a5ch9k/if_you_were_offered_immortality_but_everytime/\n",
      "17 / 25  Processing:  https://old.reddit.com/r/pics/comments/a5cbav/mickey_rourke_and_axl_rose_look_like_they_are/\n",
      "18 / 25  Processing:  https://old.reddit.com/r/BlackPeopleTwitter/comments/a5a2hb/out_here_losing_before_you_even_get_to_the/\n",
      "19 / 25  Processing:  https://old.reddit.com/r/WatchPeopleDieInside/comments/a5dflz/its_not_over_until_its_over/\n",
      "20 / 25  Processing:  https://old.reddit.com/r/worldnews/comments/a5ff63/vatican_no_3_cardinal_george_pell_convicted_on/\n",
      "21 / 25  Processing:  https://old.reddit.com/r/oddlysatisfying/comments/a5djry/timelapse_of_making_the_sushi_scene_from_isle_of/\n",
      "22 / 25  Processing:  https://old.reddit.com/r/mildlyinteresting/comments/a5h2cr/the_pole_in_this_picture_makes_it_look_like_two/\n",
      "23 / 25  Processing:  https://old.reddit.com/r/memes/comments/a5gdby/hes_a_friend_of_the_people/\n",
      "24 / 25  Processing:  https://old.reddit.com/r/NatureIsFuckingLit/comments/a5bmw3/lion_the_king_of_the_jungle_wait_for_the_yawn/\n",
      "25 / 25  Processing:  https://old.reddit.com/r/woahdude/comments/a5d2p4/guy_makes_an_upsidedown_firespewing_smoke_tornado/\n"
     ]
    }
   ],
   "source": [
    "records_c = []\n",
    "i = 1\n",
    "N = len(df['comments link'])\n",
    "for url in df['comments link']:\n",
    "    print(i, '/', N,' Processing: ', url)\n",
    "    r = requests.get(url, headers = {'User-agent': 'your bot 0.1'})\n",
    "    soup = BeautifulSoup(r.text, 'html.parser')\n",
    "    #a = soup\n",
    "    #print(soup)\n",
    "    record = html_parsing_comments(soup)\n",
    "    records_c.append(record)\n",
    "    i += 1\n",
    "    #time.sleep(2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# data transformation\n",
    "df_c = pd.DataFrame(records_c, columns=['title', 'approve', 'comment_number', 'top_comment_author', 'top_comment'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style>\n",
       "    .dataframe thead tr:only-child th {\n",
       "        text-align: right;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: left;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>approve</th>\n",
       "      <th>comment_number</th>\n",
       "      <th>top_comment_author</th>\n",
       "      <th>top_comment</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Minnesota's finest responding to noise complai...</td>\n",
       "      <td>137k</td>\n",
       "      <td>1923</td>\n",
       "      <td>oceangrown93</td>\n",
       "      <td>“I win, you go to jail.” \\n</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Smooches from his fren makes him very happy</td>\n",
       "      <td>127k</td>\n",
       "      <td>1227</td>\n",
       "      <td>rpanko</td>\n",
       "      <td>My cat always sneaks behind my dog, smacks him...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Shout out to Eric Barone (aka ConcernedApe), t...</td>\n",
       "      <td>107k</td>\n",
       "      <td>2097</td>\n",
       "      <td>Ikanan_xiii</td>\n",
       "      <td>He promised a vita port, he delivered a vita p...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>The strength of humanity</td>\n",
       "      <td>101k</td>\n",
       "      <td>639</td>\n",
       "      <td>InfoStorageBox</td>\n",
       "      <td>She’s playing life on hard mode and winning.\\n</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>It may not be the newest but I was finally abl...</td>\n",
       "      <td>98.1k</td>\n",
       "      <td>3961</td>\n",
       "      <td>ImNolan_</td>\n",
       "      <td>Where did you find Super Smash Bros Melee at? ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>In the process of building my dream home. This...</td>\n",
       "      <td>87.1k</td>\n",
       "      <td>2046</td>\n",
       "      <td>SlightlyStable</td>\n",
       "      <td>I hate you. Because jealousy of course.\\n</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>I hired a trainer for my newly-hatched bearded...</td>\n",
       "      <td>78.0k</td>\n",
       "      <td>477</td>\n",
       "      <td>Sniperkitteh_52</td>\n",
       "      <td>Please tell me one of the beardies is named Bl...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Baby otter exploring water for the first time</td>\n",
       "      <td>79.7k</td>\n",
       "      <td>495</td>\n",
       "      <td>Bovineguru</td>\n",
       "      <td>He kinda looks like a T-Rex at the beginning \\n</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>This is Clover. She’s a pippet (a cross betwee...</td>\n",
       "      <td>74.4k</td>\n",
       "      <td>632</td>\n",
       "      <td>delvach</td>\n",
       "      <td>\"Clover! Get off the counter!\"\\n\"Nope! You set...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>My eggs look like they are frowning back at me</td>\n",
       "      <td>71.9k</td>\n",
       "      <td>1053</td>\n",
       "      <td>vince1217</td>\n",
       "      <td>The best part is that you were frowning at the...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Encountered a small blind cat while hiking in ...</td>\n",
       "      <td>71.5k</td>\n",
       "      <td>1154</td>\n",
       "      <td>Fishychicken</td>\n",
       "      <td>Hey commented on your first pic. Just so every...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>I used my laser cutter/engraver to make this r...</td>\n",
       "      <td>71.5k</td>\n",
       "      <td>615</td>\n",
       "      <td>J0hn-c3na</td>\n",
       "      <td>A banjo player and his wife were awoken at 3 o...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Hydraulic press vs wolverine</td>\n",
       "      <td>67.1k</td>\n",
       "      <td>709</td>\n",
       "      <td>chelezel</td>\n",
       "      <td>The cuts are so smooth.\\n</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>War&lt;Friendship</td>\n",
       "      <td>66.7k</td>\n",
       "      <td>633</td>\n",
       "      <td>Evasion9663</td>\n",
       "      <td>General Kenobi. You survived.\\n</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Hugh Jackman had a lovely time in Korea</td>\n",
       "      <td>66.7k</td>\n",
       "      <td>1659</td>\n",
       "      <td>KingJules333</td>\n",
       "      <td>I love how they zoom in exactly when the heart...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>If you were offered immortality, but everytime...</td>\n",
       "      <td>66.1k</td>\n",
       "      <td>8522</td>\n",
       "      <td>tmankle</td>\n",
       "      <td>I would so I could spend an eternity scaring p...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Mickey Rourke, and Axl Rose, look like they ar...</td>\n",
       "      <td>58.6k</td>\n",
       "      <td>1720</td>\n",
       "      <td>OK_Compooper</td>\n",
       "      <td>I can’t tell if that’s Kathy Bates in an Axel ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Out here losing before you even get to the sta...</td>\n",
       "      <td>56.7k</td>\n",
       "      <td>589</td>\n",
       "      <td>Zetice</td>\n",
       "      <td>not true, sometimes i need a good sleep before...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>It’s not over until it’s over</td>\n",
       "      <td>56.3k</td>\n",
       "      <td>1284</td>\n",
       "      <td>Guyler-R</td>\n",
       "      <td>What were the first 2 doing? It seemed like th...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Vatican No. 3 Cardinal George Pell Convicted o...</td>\n",
       "      <td>55.1k</td>\n",
       "      <td>2168</td>\n",
       "      <td>hasharin</td>\n",
       "      <td>This news story is subject to a suppression or...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Timelapse of making the sushi scene from “Isle...</td>\n",
       "      <td>54.8k</td>\n",
       "      <td>781</td>\n",
       "      <td>justshtmypnts</td>\n",
       "      <td>Isle of Dogs Sushi Scene\\n</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>The pole in this picture makes it look like tw...</td>\n",
       "      <td>55.8k</td>\n",
       "      <td>400</td>\n",
       "      <td>Halloween_Cake</td>\n",
       "      <td>I wouldn’t know if you didn’t say anything. \\n</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>He's a friend of the people.</td>\n",
       "      <td>53.2k</td>\n",
       "      <td>358</td>\n",
       "      <td>mr_blure</td>\n",
       "      <td>My dog killed 20 people with pink shirts in tw...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>🔥 Lion, The King of the Jungle [Wait for the y...</td>\n",
       "      <td>52.8k</td>\n",
       "      <td>1012</td>\n",
       "      <td>dream0501</td>\n",
       "      <td>Tries to groom his arm. Mane keeps getting in ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>Guy makes an upside-down, fire-spewing smoke t...</td>\n",
       "      <td>52.4k</td>\n",
       "      <td>588</td>\n",
       "      <td>AutoModerator</td>\n",
       "      <td>Welcome to /r/woahdude! Please take note of a ...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                title approve comment_number  \\\n",
       "0   Minnesota's finest responding to noise complai...    137k           1923   \n",
       "1         Smooches from his fren makes him very happy    127k           1227   \n",
       "2   Shout out to Eric Barone (aka ConcernedApe), t...    107k           2097   \n",
       "3                            The strength of humanity    101k            639   \n",
       "4   It may not be the newest but I was finally abl...   98.1k           3961   \n",
       "5   In the process of building my dream home. This...   87.1k           2046   \n",
       "6   I hired a trainer for my newly-hatched bearded...   78.0k            477   \n",
       "7       Baby otter exploring water for the first time   79.7k            495   \n",
       "8   This is Clover. She’s a pippet (a cross betwee...   74.4k            632   \n",
       "9      My eggs look like they are frowning back at me   71.9k           1053   \n",
       "10  Encountered a small blind cat while hiking in ...   71.5k           1154   \n",
       "11  I used my laser cutter/engraver to make this r...   71.5k            615   \n",
       "12                       Hydraulic press vs wolverine   67.1k            709   \n",
       "13                                     War<Friendship   66.7k            633   \n",
       "14            Hugh Jackman had a lovely time in Korea   66.7k           1659   \n",
       "15  If you were offered immortality, but everytime...   66.1k           8522   \n",
       "16  Mickey Rourke, and Axl Rose, look like they ar...   58.6k           1720   \n",
       "17  Out here losing before you even get to the sta...   56.7k            589   \n",
       "18                      It’s not over until it’s over   56.3k           1284   \n",
       "19  Vatican No. 3 Cardinal George Pell Convicted o...   55.1k           2168   \n",
       "20  Timelapse of making the sushi scene from “Isle...   54.8k            781   \n",
       "21  The pole in this picture makes it look like tw...   55.8k            400   \n",
       "22                       He's a friend of the people.   53.2k            358   \n",
       "23  🔥 Lion, The King of the Jungle [Wait for the y...   52.8k           1012   \n",
       "24  Guy makes an upside-down, fire-spewing smoke t...   52.4k            588   \n",
       "\n",
       "   top_comment_author                                        top_comment  \n",
       "0        oceangrown93                        “I win, you go to jail.” \\n  \n",
       "1              rpanko  My cat always sneaks behind my dog, smacks him...  \n",
       "2         Ikanan_xiii  He promised a vita port, he delivered a vita p...  \n",
       "3      InfoStorageBox     She’s playing life on hard mode and winning.\\n  \n",
       "4            ImNolan_  Where did you find Super Smash Bros Melee at? ...  \n",
       "5      SlightlyStable          I hate you. Because jealousy of course.\\n  \n",
       "6     Sniperkitteh_52  Please tell me one of the beardies is named Bl...  \n",
       "7          Bovineguru    He kinda looks like a T-Rex at the beginning \\n  \n",
       "8             delvach  \"Clover! Get off the counter!\"\\n\"Nope! You set...  \n",
       "9           vince1217  The best part is that you were frowning at the...  \n",
       "10       Fishychicken  Hey commented on your first pic. Just so every...  \n",
       "11          J0hn-c3na  A banjo player and his wife were awoken at 3 o...  \n",
       "12           chelezel                          The cuts are so smooth.\\n  \n",
       "13        Evasion9663                    General Kenobi. You survived.\\n  \n",
       "14       KingJules333  I love how they zoom in exactly when the heart...  \n",
       "15            tmankle  I would so I could spend an eternity scaring p...  \n",
       "16       OK_Compooper  I can’t tell if that’s Kathy Bates in an Axel ...  \n",
       "17             Zetice  not true, sometimes i need a good sleep before...  \n",
       "18           Guyler-R  What were the first 2 doing? It seemed like th...  \n",
       "19           hasharin  This news story is subject to a suppression or...  \n",
       "20      justshtmypnts                         Isle of Dogs Sushi Scene\\n  \n",
       "21     Halloween_Cake     I wouldn’t know if you didn’t say anything. \\n  \n",
       "22           mr_blure  My dog killed 20 people with pink shirts in tw...  \n",
       "23          dream0501  Tries to groom his arm. Mane keeps getting in ...  \n",
       "24      AutoModerator  Welcome to /r/woahdude! Please take note of a ...  "
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_c"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "df_c.to_csv('reddit_data_extraction_2.csv', sep=',', encoding='UTF-8')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: Do not use the development server in a production environment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "[2018-12-12 14:16:00,616] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:00] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:00,862] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'sentiment-pie.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:00] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:01,358] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:01] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:02,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:02] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:02] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:03] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:03] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n",
      "[2018-12-12 14:16:03,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:03] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:04,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:04] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:05,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:05] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2018-12-12 14:16:05,375] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'sentiment-pie.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:05] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:06,359] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:06] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:07,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:07] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:08,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:08] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:09,359] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:09] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:10,360] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:10] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:10,372] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'sentiment-pie.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:10] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:11,360] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [12/Dec/2018 14:16:11] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:12,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:12] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:13,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:13] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:14,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:14] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:15,363] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:15] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:15,366] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'sentiment-pie.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:15] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:16,360] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:16] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:17,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:17] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:18,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [12/Dec/2018 14:16:18] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:19,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:19] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:20,360] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:20] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:20,372] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'sentiment-pie.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:20] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:21,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:21] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:22,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:22] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:23,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:23] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:24,360] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:24] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:25,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [12/Dec/2018 14:16:25] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:25,374] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'sentiment-pie.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:25] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:26,360] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:26] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:27,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:27] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:28,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:28] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:29,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:29] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:30,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:30] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:30,375] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'sentiment-pie.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:30] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:31,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [12/Dec/2018 14:16:31] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:32,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:32] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:33,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:33] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:34,360] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:34] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:35,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:35] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:35,375] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'sentiment-pie.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:35] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:36,359] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:36] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:37,360] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:37] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:38,360] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [12/Dec/2018 14:16:38] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:39,361] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:39] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:40,360] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:40] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:40,376] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'sentiment-pie.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:40] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:41,364] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:41] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:42,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:42] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2018-12-12 14:16:43,362] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"D:\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 904, in dispatch\n",
      "    for component_registration in self.callback_map[target_id]['inputs']:\n",
      "KeyError: 'live-graph.figure'\n",
      "127.0.0.1 - - [12/Dec/2018 14:16:43] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "def generate_table(dataframe, max_rows=10):\n",
    "    return html.Table(\n",
    "        # Header\n",
    "        [html.Tr([html.Th(col) for col in dataframe.columns])] +\n",
    "\n",
    "        # Body\n",
    "        [html.Tr([\n",
    "            html.Td(dataframe.iloc[i][col]) for col in dataframe.columns\n",
    "        ]) for i in range(min(len(dataframe), max_rows))]\n",
    "    )\n",
    "\n",
    "\n",
    "external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']\n",
    "\n",
    "app = dash.Dash(__name__, external_stylesheets=external_stylesheets)\n",
    "\n",
    "app.layout = html.Div(children=[\n",
    "    html.H4(children='Reddit top threads'),\n",
    "    generate_table(df)\n",
    "])\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
